[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = 'qspec'
version = '0.5.0'
description = 'Physics toolbox for laser spectroscopy'
readme = 'README.md'
requires-python = '>=3.12'
license = 'MIT'
license-files = ['LICENSE']
# license = {file = 'LICENSE'}

keywords = ['physics', 'simulation', 'data analysis', 'atomic structure', 'laser spectroscopy', 'laser cooling', 'coherent interaction', 'quantum computing']
authors = [
    {name = 'Patrick Müller', email = 'pamueller.ikp@gmail.com'},
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    # 'License :: OSI Approved :: MIT License',
    'Operating System :: Microsoft :: Windows',
    'Programming Language :: C++',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Scientific/Engineering :: Physics',
]
dependencies = [
    'matplotlib',
    'numpy >= 2.0.2',
    'scipy >= 1.13.1',
    'sympy'
]

[project.urls]
homepage = 'https://patmlr.github.io/qspec/'
documentation = 'https://patmlr.github.io/qspec/doc/doc.html'
download = 'https://pypi.org/project/qspec/#files'
source = 'https://github.com/patmlr/qspec'
tracker = 'https://github.com/patmlr/qspec/issues'

[tool.hatch.metadata.files]
include = ["qspec/**"]

# Hatchling wheel build config
[tool.hatch.build.targets.wheel]
include = ["qspec/**"]
exclude = ["qspec/_cpp/qspec_cpp/**"]
pure_python = false

[tool.hatch.build.targets.sdist]
include = [
    "qspec/**",
]
exclude = ["qspec/_cpp/qspec_cpp/build/**"]

[tool.ruff]
extend-exclude = [
    "__pycache__",
    "docs/*",
    "__init__.py",
]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "ANN",
    "E",
    "F",
    "I",
    "ICN",
    "ISC",
    "NPY",
    "Q",
    "RET",
    "RUF",
    "SIM",
    "TC",
    "TID",
    "UP",
]

ignore = [
    "ANN003",
    "ANN401",
    "E741",
    "RUF012",
]

[tool.ruff.lint.isort]
known-first-party = ["qspec"]
